### ISSUE TITLE
Improving workflow

### ISSUE THREAD

**Issue by Fixer-007** [octacian/multihome#1]
If you have just one home, typing /home should be enough to bring you back to home. This will help avoid typing home name.

**Comment by octacian** [comment]
a8b2822e65666429278405d7814a94360e9f20c4

I considered adding the ability to also set a default home to teleport to even if you have multiple homes, but I'm not sure at this point. It would require some adjustments and another brand new chatcommand for override mode. See README just above "None/Deprecate" compatibility info for specifics.
