### ISSUE TITLE
this mod does not working in single player

### ISSUE THREAD

**Issue by InterVi** [octacian/multihome#3]
Not show settings in GUI, not working mod commands. Minetest 0.4.16

**Comment by octacian** [comment]
1. I have not implemented a `settingtypes.txt` file yet in order to register settings in the GUI
2. What do you mean the mod commands aren't working? Don't forget to try the `/multihome` command, the `/home` command is only overridden if MultiHome is configured to do so

**Comment by octacian** [comment]
@InterVi Could you try the things mentioned above and let me know what happens? You may also need to grant yourself the `multihome` privilege, but that is only if you haven't configured the mod to override the default `home` commands.

If I don't get a response within the next few days I'll be closing the issue as I know that it works fine for me. Thanks!

**Comment by octacian** [comment]
Well, due to having received no response, I am going to close this issue. Should you see this, please read my above message and review the functionality of the mod as documented in the README. If you are still having trouble, you are welcome to reopen this issue.
